/**
 * Lista centralizada de fuentes disponibles para textos personalizados
 */

export const AVAILABLE_FONTS = [
  { label: "Oxanium (Gamer)", value: "Oxanium, sans-serif" },
  { label: "Orbitron (Tech)", value: "Orbitron, sans-serif" },
  { label: "Audiowide (Display)", value: "Audiowide, cursive" },
  { label: "Press Start 2P (Retro)", value: '"Press Start 2P", cursive' },
  { label: "Rajdhani (Display)", value: "Rajdhani, sans-serif" },
  { label: "Exo 2", value: '"Exo 2", sans-serif' },
  { label: "Barlow", value: "Barlow, sans-serif" },
  { label: "Montserrat", value: "Montserrat, sans-serif" },
  { label: "Teko", value: "Teko, sans-serif" },
  { label: "Anton", value: "Anton, sans-serif" },
  { label: "Roboto", value: "Roboto, sans-serif" },
  { label: "Lato", value: "Lato, sans-serif" },
  { label: "Oswald", value: "Oswald, sans-serif" },
  { label: "Bebas Neue", value: '"Bebas Neue", cursive' },
  { label: "Poppins", value: "Poppins, sans-serif" },
  { label: "Fira Sans", value: '"Fira Sans", sans-serif' },
  { label: "Rubik", value: "Rubik, sans-serif" },
  { label: "Russo One (Gamer)", value: '"Russo One", sans-serif' },
  { label: "VT323 (Retro)", value: '"VT323", monospace' },
  { label: "Share Tech Mono", value: '"Share Tech Mono", monospace' },
  { label: "Bangers (Cómic)", value: '"Bangers", cursive' },
  { label: "Permanent Marker", value: '"Permanent Marker", cursive' },
  { label: "Luckiest Guy", value: '"Luckiest Guy", cursive' },
  { label: "Archivo Black", value: '"Archivo Black", sans-serif' },
  { label: "Chakra Petch", value: '"Chakra Petch", sans-serif' },
  { label: "Titillium Web", value: '"Titillium Web", sans-serif' },
  { label: "Unica One", value: '"Unica One", cursive' },
  { label: "Syncopate", value: '"Syncopate", sans-serif' },
  { label: "Saira", value: '"Saira", sans-serif' },
  { label: "Coda Caption", value: '"Coda Caption", sans-serif' },
  { label: "Black Ops One", value: '"Black Ops One", cursive' },
  { label: "Staatliches", value: '"Staatliches", cursive' },
  { label: "Barlow Condensed", value: '"Barlow Condensed", sans-serif' },
] as const;
